#pragma once
#define WORKLOAD_FABRIC_VERSION_MAJOR 1
#define WORKLOAD_FABRIC_VERSION_MINOR 0
#define WORKLOAD_FABRIC_VERSION_PATCH 0
#define WORKLOAD_FABRIC_VERSION_STRING "1.0.0"
#define WORKLOAD_FABRIC_VERSION_TAG   "v1.0.0"
namespace wf { inline constexpr const char* kVersion = WORKLOAD_FABRIC_VERSION_STRING; }
