#include "workload_fabric/outcome.hpp"

namespace wf {
namespace {
inline constexpr const char* kOs[] = {
  "ALLOW",
  "DEFER",
  "BLOCKED_DEPENDENCY",
  "BLOCKED_RESOURCE_CONTRACT",
  "REJECT_STALE_EPOCH",
  "REJECT_STALE_BOOT",
  "REJECT_STALE_WORKLOAD_GENERATION",
  "REJECT_STALE_EPISODE",
  "REJECT_STALE_RESOURCE_CONTRACT",
  "REJECT_STALE_DEPENDENCY",
  "REJECT_STALE_PRIORITY",
  "REJECT_STALE_PROGRESS",
  "REJECT_STALE_MIGRATION",
  "REJECT_TERMINAL",
  "REJECT_CANCELLED",
  "REJECT_RESTART_LIMIT",
  "REJECT_MIGRATION_INELIGIBLE",
  "REJECT_NOT_SUSPENDED",
  "REJECT_NOT_RESUMABLE",
  "REJECT_INVALID_TRANSITION",
  "REJECT_PROGRESS_DOUBLE_COUNT",
  "REJECT_PROGRESS_REGRESSION",
  "REJECT_RESOURCE_DOUBLE_RELEASE",
  "REJECT_DUPLICATE_WORKLOAD",
  "REJECT_WORKLOAD_NOT_FOUND",
  "REJECT_CROSS_WORKLOAD",
  "REJECT_IMMUTABLE_CONTRACT",
  "REJECT_PRIORITY_NOT_MUTABLE",
  "REJECT_NOT_BLOCKED",
  "REJECT_EPISODE_INELIGIBLE",
  "REJECT_NOT_RUNNABLE",
  "REJECT_UNKNOWN_DEPENDENCY",
  "REJECT_DEGRADED_POLICY",
  "REJECT_COMPLETION_POLICY",
  "REJECT_UNKNOWN",
  "REVALIDATION_REQUIRED",
  "UNKNOWN",
};
}  // namespace
std::string_view outcomeName(Outcome o) noexcept {
  auto i = static_cast<std::size_t>(o);
  if (i >= sizeof(kOs) / sizeof(kOs[0])) return "INVALID";
  return kOs[i];
}
}  // namespace wf
